name: nexstream
description: A new Flutter project for a Nexstream login screen.

# Prevent accidental publication to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  video_player: ^2.5.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.6.0
  flutter_web_auth: ^0.4.0
  provider: ^6.0.5
  font_awesome_flutter: ^10.1.0
  another_flushbar: ^1.10.30
  carousel_slider: ^4.1.0
  image_picker: ^0.8.4+4
  dio: ^5.0.0
  chewie: ^1.2.2
  youtube_player_flutter: ^8.0.0
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Include any assets your application uses.
  assets:
    - assets/profile_placeholder.jpg
    - assets/sample_video.mp4

  # Include any fonts you are using.
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
