// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiSabwx87DrMV1TNvfz0gXLhGRpgZZdJA',
    appId: '1:505918935158:web:e16aed53cbea5077bacf57',
    messagingSenderId: '505918935158',
    projectId: 'driving-licence-fe70e',
    authDomain: 'driving-licence-fe70e.firebaseapp.com',
    databaseURL: 'https://driving-licence-fe70e-default-rtdb.firebaseio.com',
    storageBucket: 'driving-licence-fe70e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDbeoIctMRYlFcGIbCFdRBX38GEvifr7c',
    appId: '1:505918935158:android:2d01fece2b2fce49bacf57',
    messagingSenderId: '505918935158',
    projectId: 'driving-licence-fe70e',
    databaseURL: 'https://driving-licence-fe70e-default-rtdb.firebaseio.com',
    storageBucket: 'driving-licence-fe70e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQITViRgkeieiMp1Bo7Y3zpTfG3iKSX-k',
    appId: '1:505918935158:ios:9c63e2ab0a048545bacf57',
    messagingSenderId: '505918935158',
    projectId: 'driving-licence-fe70e',
    databaseURL: 'https://driving-licence-fe70e-default-rtdb.firebaseio.com',
    storageBucket: 'driving-licence-fe70e.appspot.com',
    iosBundleId: 'com.example.nextstream1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQITViRgkeieiMp1Bo7Y3zpTfG3iKSX-k',
    appId: '1:505918935158:ios:9c63e2ab0a048545bacf57',
    messagingSenderId: '505918935158',
    projectId: 'driving-licence-fe70e',
    databaseURL: 'https://driving-licence-fe70e-default-rtdb.firebaseio.com',
    storageBucket: 'driving-licence-fe70e.appspot.com',
    iosBundleId: 'com.example.nextstream1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiSabwx87DrMV1TNvfz0gXLhGRpgZZdJA',
    appId: '1:505918935158:web:037678a2696d2163bacf57',
    messagingSenderId: '505918935158',
    projectId: 'driving-licence-fe70e',
    authDomain: 'driving-licence-fe70e.firebaseapp.com',
    databaseURL: 'https://driving-licence-fe70e-default-rtdb.firebaseio.com',
    storageBucket: 'driving-licence-fe70e.appspot.com',
  );

}